/* Sample book of business for Benefits Desk. Every company, person, carrier and figure is fictional. */
const DATA = {
  firm: "Crestline Benefit Partners",
  users: [
    { id: "mh", name: "Morgan Hale", role: "Principal", email: "morgan.hale@crestline.example" },
    { id: "ps", name: "Priya Shah", role: "Account Manager", email: "priya.shah@crestline.example" },
    { id: "lo", name: "Luis Ortega", role: "Benefits Analyst", email: "luis.ortega@crestline.example" },
  ],
  groups: [
    { id: "trinity-oak", name: "Trinity Oak Dental Group", industry: "Dental practices", hq: "Frisco, TX", locations: ["Frisco", "McKinney", "Denton"],
      eligible: 38, enrolled: 34, funding: "Fully insured", carrier: "Meridian Health Plans", plan: "Gold PPO 1500", renewal: "2026-11-01",
      annual: 419460, renewalAnnual: 481728, am: "Priya Shah", stage: "Quotes in", stageKind: "info", health: 72 },
    { id: "cedar-ridge", name: "Cedar Ridge Logistics", industry: "Transportation & warehousing", hq: "Columbus, OH", locations: ["Columbus, OH", "Indianapolis, IN", "Louisville, KY", "Nashville, TN"],
      eligible: 2410, enrolled: 2140, funding: "Self-funded", carrier: "Northstar (TPA) · MedFirst Rx · Great Lakes Re", plan: "Choice PPO / HDHP", renewal: "2027-01-01",
      annual: 31820000, renewalAnnual: 34150000, am: "Morgan Hale", stage: "Bids in", stageKind: "info", health: 64 },
    { id: "harbor-point", name: "Harbor Point Hospitality", industry: "Hotels & resorts", hq: "Galveston, TX", locations: ["Galveston", "Kemah"],
      eligible: 131, enrolled: 94, funding: "Fully insured", carrier: "Meridian Health Plans", plan: "Silver PPO 3000", renewal: "2026-12-01",
      annual: 842600, renewalAnnual: 936930, am: "Priya Shah", stage: "Renewal received", stageKind: "warn", health: 58 },
    { id: "northfield", name: "Northfield Precision Manufacturing", industry: "Manufacturing", hq: "Rochester, MN", locations: ["Rochester", "Winona"],
      eligible: 1390, enrolled: 1260, funding: "Self-funded", carrier: "ClearPath TPA · Clarus Rx · Harborstone", plan: "HDHP + HSA", renewal: "2027-07-01",
      annual: 17940000, renewalAnnual: null, am: "Morgan Hale", stage: "Mid-year claims review", stageKind: "", health: 86 },
    { id: "prairie-wind", name: "Prairie Wind Credit Union", industry: "Financial services", hq: "Wichita, KS", locations: ["Wichita", "Hutchinson", "Salina"],
      eligible: 162, enrolled: 146, funding: "Fully insured", carrier: "Pioneer Health", plan: "PPO 2000 / HSA 3500", renewal: "2027-03-01",
      annual: 1284000, renewalAnnual: null, am: "Luis Ortega", stage: "On track", stageKind: "ok", health: 91 },
    { id: "bluebonnet", name: "Bluebonnet Veterinary Partners", industry: "Veterinary clinics", hq: "Austin, TX", locations: ["Austin", "Round Rock", "Georgetown", "San Marcos"],
      eligible: 74, enrolled: 61, funding: "Level-funded", carrier: "Summit Care Health", plan: "Level-funded PPO 2500", renewal: "2027-01-01",
      annual: 528400, renewalAnnual: null, am: "Luis Ortega", stage: "Renewal expected Oct 15", stageKind: "", health: 80 },
    { id: "red-river", name: "Red River HVAC Services", industry: "Construction trades", hq: "Sherman, TX", locations: ["Sherman"],
      eligible: 27, enrolled: 22, funding: "Fully insured", carrier: "Keystone Blue", plan: "Blue Advantage PPO 2000", renewal: "2027-01-01",
      annual: 196300, renewalAnnual: null, am: "Priya Shah", stage: "Census requested", stageKind: "warn", health: 69 },
    { id: "alder-finch", name: "Alder & Finch LLP", industry: "Legal services", hq: "Dallas, TX", locations: ["Dallas"],
      eligible: 61, enrolled: 57, funding: "ICHRA", carrier: "Individual market (ICHRA)", plan: "Age-banded allowance", renewal: "2027-01-01",
      annual: 612000, renewalAnnual: null, am: "Morgan Hale", stage: "Allowance review", stageKind: "", health: 88 },
  ],

  activity: [
    { t: "7:42 AM", icon: "columns", kind: "info", title: "Read 4 carrier quotes for Trinity Oak Dental", body: "6 plans extracted and set side by side against the Meridian renewal. Closest like-for-like saves $48,084 a year; the HSA option saves $111,024.", link: "#/marketing/trinity-oak" },
    { t: "7:40 AM", icon: "scale", kind: "violet", title: "Normalized 9 specialist bids for Cedar Ridge Logistics", body: "TPA, PBM and stop-loss bids converted to annual cost on 2,140 employees. 2 lasers and 2 spread-pricing PBMs flagged.", link: "#/marketing/cedar-ridge" },
    { t: "7:15 AM", icon: "alert", kind: "crit", title: "3 billing errors on the Meridian invoice for Harbor Point", body: "A terminated employee still billed and 2 wrong tiers. $1,842 a month overbilled.", link: "#/reconciliation" },
    { t: "6:58 AM", icon: "dollar", kind: "warn", title: "Keystone Blue paid $412 short on Red River HVAC", body: "September statement paid on 19 lives; 22 are enrolled.", link: "#/commissions" },
    { t: "6:30 AM", icon: "shield", kind: "ok", title: "Medicare Part D notices drafted for 6 groups", body: "Due to employees by October 15. Creditable coverage determined from each plan's SBC.", link: "#/compliance" },
    { t: "Yesterday", icon: "inbox", kind: "info", title: "Triaged 11 emails from HR contacts", body: "7 replies drafted, 3 eligibility changes queued for carriers, 1 escalated.", link: "#/inbox" },
  ],

  tasks: [
    { title: "Pick a recommendation for Trinity Oak", due: "2026-10-09", why: "Meridian needs the signed renewal back by Oct 9", link: "#/marketing/trinity-oak", owner: "Priya Shah" },
    { title: "Get missing census details from Trinity Oak HR", due: "2026-09-18", why: "1 date of birth and 1 coverage election to confirm", link: "#/census", owner: "Luis Ortega" },
    { title: "Review Atlas stop-loss lasers with Cedar Ridge CFO", due: "2026-09-25", why: "2 lasers ($750K, $500K) behind the lowest premium", link: "#/marketing/cedar-ridge", owner: "Morgan Hale" },
    { title: "Send eligibility term to Meridian for Harbor Point", due: "2026-09-17", why: "Terminated 08/14, still billed in September", link: "#/enrollment", owner: "Priya Shah" },
    { title: "Approve Part D notices", due: "2026-10-01", why: "6 groups, drafts ready", link: "#/compliance", owner: "Luis Ortega" },
  ],

  renewals: [
    { group: "trinity-oak", received: "2026-09-02", current: 419460, renewal: 481728, deadline: "2026-10-09", stage: "Marketing: 4 of 5 carriers quoted", drivers: [["Medical trend", 8.9], ["Group experience", 3.4], ["Age / demographic", 1.6], ["Fees", 0.9]] },
    { group: "harbor-point", received: "2026-09-10", current: 842600, renewal: 936930, deadline: "2026-11-06", stage: "Analysis ready", drivers: [["Medical trend", 7.8], ["Group experience", 2.1], ["Age / demographic", 0.6], ["Fees", 0.7]] },
    { group: "cedar-ridge", received: "2026-08-21", current: 31820000, renewal: 34150000, deadline: "2026-11-15", stage: "Specialist bids in: 9 of 9", drivers: [["Claims trend", 6.1], ["Stop-loss renewal", 0.8], ["PBM renewal", 0.3], ["Admin fees", 0.1]] },
    { group: "bluebonnet", received: null, current: 528400, renewal: null, deadline: "2026-11-20", stage: "Renewal expected Oct 15", drivers: [] },
    { group: "red-river", received: null, current: 196300, renewal: null, deadline: "2026-12-01", stage: "Census requested from HR", drivers: [] },
    { group: "alder-finch", received: null, current: 612000, renewal: null, deadline: "2026-11-30", stage: "2027 allowance modeling", drivers: [] },
  ],

  rfp: {
    "trinity-oak": {
      title: "Trinity Oak Dental: November 2026 marketing", effective: "2026-11-01", due: "2026-09-30", type: "fully-insured",
      invited: [
        { carrier: "Meridian Health Plans", status: "Renewal received", kind: "ok", file: "Meridian_Renewal_MHP-448120_Nov2026.pdf" },
        { carrier: "Keystone Blue", status: "Quoted", kind: "ok", file: "KeystoneBlue_Quote_KB-Q-2026-77831.pdf" },
        { carrier: "Summit Care Health", status: "Quoted", kind: "ok", file: "Summit Care - Trinity Oak Dental proposal.pdf" },
        { carrier: "Pioneer Health", status: "Quoted", kind: "ok", file: "Pioneer Health quote PH-10-2291.pdf" },
        { carrier: "Lakeside Health", status: "Declined: under 50 enrolled", kind: "crit", file: null },
      ],
      tiers: { EE: 18, ES: 6, EC: 5, FAM: 5 },
    },
    "cedar-ridge": {
      title: "Cedar Ridge Logistics: 2027 self-funded marketing", effective: "2027-01-01", due: "2026-10-15", type: "self-funded",
      employees: 2140, singles: 1210, families: 930,
      rx: { brandAWP: 3900000, genericAWP: 2600000, specialtyAWP: 3100000 },
      claimantsOver250k: 6, claimsBudget: 23400000,
      files: ["Northstar Administrators - renewal.pdf", "ClearPath TPA proposal.pdf", "Anchor Benefit Administrators bid.pdf",
        "MedFirst Rx renewal.pdf", "Clarus Rx PBM proposal.pdf", "Vantage Pharmacy Solutions.pdf",
        "Great Lakes Re - stop loss renewal.pdf", "Harborstone Specialty stop loss quote.pdf", "Atlas Stop Loss proposal.pdf"],
    },
  },

  inbox: [
    { id: 1, from: "Dana Whitley", org: "Harbor Point Hospitality", email: "dwhitley@harborpoint.example", time: "8:12 AM", subject: "New hire - benefits start?",
      body: "Hi Priya,\n\nWe hired Marcus Bell as a front desk supervisor, start date 9/8. He wants medical for himself and his wife. When does his coverage start and what do I need from him?\n\nThanks,\nDana",
      intent: "New hire enrollment", conf: 0.97, fields: [["Employee", "Marcus Bell"], ["Hire date", "09/08/2026"], ["Coverage", "Employee + spouse"], ["Waiting period", "1st of month after 30 days"], ["Coverage starts", "11/01/2026"], ["Enrollment deadline", "10/08/2026"]],
      action: "Enrollment link sent, window tracked", draft: "Hi Dana,\n\nThanks for letting us know. With Harbor Point's first-of-the-month-after-30-days waiting period, Marcus's coverage starts November 1. He has until October 8 to enroll.\n\nI've sent him the enrollment link for Employee + Spouse on the Silver PPO 3000. He will need his wife's date of birth and Social Security number to finish.\n\nI'll confirm once the carrier has processed it.\n\nPriya" },
    { id: 2, from: "Tom Reyes", org: "Red River HVAC Services", email: "treyes@redriverhvac.example", time: "7:55 AM", subject: "Termination - Jake Wilson",
      body: "Priya - Jake Wilson's last day was Friday 9/11. Please take him off the plan. He said he might want COBRA.\n\nTom",
      intent: "Termination + COBRA", conf: 0.95, fields: [["Employee", "Jake Wilson"], ["Last day", "09/11/2026"], ["Coverage ends", "09/30/2026"], ["COBRA notice due", "10/25/2026"], ["Carrier", "Keystone Blue"]],
      action: "Term queued for Keystone, COBRA vendor notified", draft: "Hi Tom,\n\nGot it. Jake Wilson's coverage will end September 30. I've sent the termination to Keystone Blue and notified the COBRA administrator, who will mail his election notice well before the October 25 deadline.\n\nNothing else is needed from you.\n\nPriya" },
    { id: 3, from: "Angela Mercer", org: "Trinity Oak Dental Group", email: "amercer@trinityoak.example", time: "Yesterday", subject: "RE: renewal - what are our options?",
      body: "Priya,\n\nDr. Patel saw the 14.8% increase and wants to know what else is out there before we sign anything. Can you send options by next week? We'd like to keep the same doctors if possible.\n\nAngela",
      intent: "Renewal question", conf: 0.92, fields: [["Group", "Trinity Oak Dental Group"], ["Renewal change", "+14.8%"], ["Decision deadline", "10/09/2026"], ["Priority", "Keep current doctors"]],
      action: "Linked to marketing case, network check requested", draft: "Hi Angela,\n\nWe already have quotes back from Keystone Blue, Summit Care and Pioneer Health, and a side-by-side against the Meridian renewal is ready. The closest like-for-like plan saves about $48,000 a year, and moving to an HSA plan would save about $111,000.\n\nBefore I send it, I'm running Dr. Patel's top providers through each carrier's network so we only recommend plans that keep your doctors. Could we review on Monday?\n\nPriya" },
    { id: 4, from: "Kevin Doyle", org: "Prairie Wind Credit Union", email: "kdoyle@prairiewind.example", time: "Yesterday", subject: "ID card never arrived",
      body: "Hello, I'm an employee at Prairie Wind. I enrolled in August and still have no insurance card. I have a doctor's appointment Thursday. Can you help?\n\nKevin Doyle",
      intent: "ID card request", conf: 0.98, fields: [["Member", "Kevin Doyle"], ["Carrier", "Pioneer Health"], ["Effective", "09/01/2026"], ["Member ID", "PH8820417 (from eligibility file)"]],
      action: "Temporary card requested from carrier portal", draft: "Hi Kevin,\n\nYour coverage with Pioneer Health has been active since September 1. Your member ID is PH8820417, and I've attached a temporary ID card you can show at Thursday's appointment. Your permanent card has been reordered and should arrive within 7 to 10 days.\n\nLuis" },
    { id: 5, from: "Rachel Kim", org: "Bluebonnet Veterinary Partners", email: "rkim@bluebonnetvet.example", time: "Yesterday", subject: "Adding my newborn",
      body: "Hi! I had my baby on September 3rd (Olivia Kim). How do I add her to my insurance? I'm currently on employee only.\n\nRachel",
      intent: "Qualifying life event", conf: 0.96, fields: [["Employee", "Rachel Kim"], ["Event", "Birth"], ["Event date", "09/03/2026"], ["Change", "Employee only to Employee + child"], ["Deadline to add", "10/03/2026"], ["Coverage retro to", "09/03/2026"]],
      action: "Life event form pre-filled, deadline tracked", draft: "Hi Rachel,\n\nCongratulations! You have until October 3 to add Olivia, and her coverage will go back to her birth date on September 3.\n\nI've pre-filled the change form with Employee + Child. It just needs your signature and a copy of the birth certificate or hospital record.\n\nLuis" },
    { id: 6, from: "Mark Delgado", org: "Cedar Ridge Logistics", email: "mdelgado@cedarridge.example", time: "Sep 14", subject: "Stop loss - why is our renewal up?",
      body: "Morgan,\n\nOur CFO is asking why Great Lakes raised the specific rates and added a laser. Do we have alternatives before the board meeting on the 24th?\n\nMark",
      intent: "Renewal question (self-funded)", conf: 0.9, fields: [["Group", "Cedar Ridge Logistics"], ["Topic", "Stop-loss renewal + laser"], ["Meeting", "09/24/2026 board meeting"], ["Bids available", "3 stop-loss, 3 TPA, 3 PBM"]],
      action: "Linked to self-funded marketing case", draft: "Mark,\n\nYes. We have stop-loss bids back from Harborstone Specialty and Atlas alongside the Great Lakes renewal. Harborstone comes in about $610,000 a year below Great Lakes at the same $250,000 deductible with no lasers. Atlas is cheaper still, but carries two lasers and a higher deductible, so its real exposure is higher.\n\nI'll have a one-page comparison for the CFO ahead of the 24th.\n\nMorgan" },
  ],

  recon: [
    { group: "harbor-point", source: "Meridian invoice Sep 2026", who: "Derek Keller", issue: "Billed after termination", detail: "Terminated 08/14/2026; still billed Employee + spouse", monthly: 1316, sev: "crit" },
    { group: "harbor-point", source: "Meridian invoice Sep 2026", who: "Lena Ruiz", issue: "Wrong tier", detail: "Enrolled Employee only; billed Family", monthly: 402, sev: "warn" },
    { group: "harbor-point", source: "Meridian invoice Sep 2026", who: "Omar Haddad", issue: "Wrong tier", detail: "Enrolled Employee + child; billed Employee + spouse", monthly: 124, sev: "warn" },
    { group: "prairie-wind", source: "Payroll register 9/15", who: "Kevin Doyle", issue: "Election with no deduction", detail: "Enrolled 09/01 Employee only; $0 withheld on 2 paychecks", monthly: 188, sev: "crit" },
    { group: "bluebonnet", source: "Payroll register 9/12", who: "Samuel Ortiz", issue: "Deduction does not match election", detail: "Elected Family ($412.50 per pay); withheld Employee + spouse ($286.00)", monthly: 253, sev: "warn" },
    { group: "trinity-oak", source: "Meridian invoice Sep 2026", who: "(not on roster)", issue: "Unknown member billed", detail: "\"J. Castillo\" billed Employee only; no one by that name on the roster", monthly: 646, sev: "crit" },
    { group: "red-river", source: "Keystone eligibility file", who: "Jake Wilson", issue: "Termination not sent", detail: "Last day 09/11; still active with the carrier", monthly: 571, sev: "warn" },
  ],

  commissions: [
    { carrier: "Meridian Health Plans", group: "trinity-oak", month: "Sep 2026", basis: "5% of premium", expected: 1747.75, paid: 1747.75 },
    { carrier: "Meridian Health Plans", group: "harbor-point", month: "Sep 2026", basis: "5% of premium", expected: 3510.83, paid: 3419.20 },
    { carrier: "Keystone Blue", group: "red-river", month: "Sep 2026", basis: "$25 PEPM", expected: 550.00, paid: 475.00 },
    { carrier: "Pioneer Health", group: "prairie-wind", month: "Sep 2026", basis: "4.5% of premium", expected: 4815.00, paid: 4815.00 },
    { carrier: "Summit Care Health", group: "bluebonnet", month: "Sep 2026", basis: "$28 PEPM", expected: 1708.00, paid: 1708.00 },
    { carrier: "Keystone Blue", group: "red-river", month: "Aug 2026", basis: "$25 PEPM", expected: 550.00, paid: 213.00, note: "Chargeback: 2 retro terms from June" },
    { carrier: "Summit Care Health", group: "bluebonnet", month: "Aug 2026", basis: "$28 PEPM", expected: 1708.00, paid: 0, note: "Not received" },
  ],

  compliance: [
    { item: "Medicare Part D creditable coverage notice", due: "2026-10-15", groups: 6, done: 0, drafted: 6, kind: "Notice to employees", auto: "Coverage status determined from each plan's SBC; notices drafted" },
    { item: "Gag clause prohibition attestation (CAA)", due: "2026-12-31", groups: 8, done: 3, drafted: 5, kind: "Filing with CMS", auto: "Carrier and TPA contracts checked for gag clauses" },
    { item: "Summary of Benefits and Coverage at open enrollment", due: "2026-10-02", groups: 1, done: 0, drafted: 1, kind: "Distribution", auto: "SBCs pulled from carrier portals for Trinity Oak" },
    { item: "ACA Forms 1095-C to employees", due: "2027-03-02", groups: 3, done: 0, drafted: 0, kind: "Reporting (ALE groups)", auto: "Monthly offer and affordability codes building from payroll" },
    { item: "Form 5500 (plans with 100+ participants)", due: "2027-07-31", groups: 4, done: 0, drafted: 0, kind: "Filing", auto: "Schedule A data requested from carriers" },
    { item: "PCORI fee (self-funded plans)", due: "2027-07-31", groups: 2, done: 0, drafted: 0, kind: "IRS Form 720", auto: "Average covered lives calculated from monthly enrollment" },
    { item: "Prescription drug data collection (RxDC)", due: "2027-06-01", groups: 8, done: 0, drafted: 0, kind: "Filing with CMS", auto: "D1 to D8 files requested from PBMs and carriers" },
  ],

  enrollment: {
    windows: [
      { group: "harbor-point", who: "Marcus Bell", event: "New hire", date: "2026-09-08", deadline: "2026-10-08", status: "Link sent" },
      { group: "bluebonnet", who: "Rachel Kim", event: "Birth", date: "2026-09-03", deadline: "2026-10-03", status: "Form pre-filled" },
      { group: "prairie-wind", who: "Alicia Grant", event: "New hire", date: "2026-08-24", deadline: "2026-09-23", status: "Not started" },
      { group: "trinity-oak", who: "Hannah Lowe", event: "Marriage", date: "2026-08-22", deadline: "2026-09-21", status: "Not started" },
      { group: "red-river", who: "Jake Wilson", event: "Termination", date: "2026-09-11", deadline: "2026-09-30", status: "Sent to carrier" },
    ],
    sync: [
      { group: "harbor-point", carrier: "Meridian Health Plans", who: "Derek Keller", ours: "Terminated 08/14/2026", theirs: "Active: Employee + spouse", fix: "Send termination effective 08/31/2026" },
      { group: "trinity-oak", carrier: "Meridian Health Plans", who: "Hannah Lowe", ours: "Employee + spouse (pending event)", theirs: "Employee only", fix: "Send tier change effective 09/01/2026" },
      { group: "prairie-wind", carrier: "Pioneer Health", who: "Kevin Doyle", ours: "Active since 09/01/2026", theirs: "Active since 09/01/2026", fix: null },
      { group: "bluebonnet", carrier: "Summit Care Health", who: "Samuel Ortiz", ours: "Family", theirs: "Employee + spouse", fix: "Send tier change effective 09/01/2026" },
    ],
  },
};
